### ISSUE TITLE
The Plugin is not working with SonarQube 9.x.

### ISSUE THREAD

**Issue by igor-antonacci** [evolution-gaming/sonar-erlang#30]
As from a previous issue, the plugin cannot be loaded from SonarQube 9.9.0 (LTS).

Any plan to make it compatible with latest SQ version?

Thank you

**Comment by ghostbody** [comment]
I have try to fix it and work well. Fell free to have a try.

https://github.com/ghostbody/sonar-erlang/tree/v1.4-fix

**Comment by vooolll** [comment]
Try, 1.6 version, should work with 9.9 sonar
